# Development-specific settings
# This file overrides _config.yml for local builds.
# It sets baseurl to /preview so links work correctly 
# when served from the /preview endpoint locally.
baseurl: "/preview"
# Use local URL for development
url: "http://localhost:8000"
relative_permalinks: false
